CREATE DATABASE IF NOT EXISTS printing_db;
USE printing_db;

CREATE TABLE IF NOT EXISTS Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  UserName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Materials (
  MaterialID INT PRIMARY KEY AUTO_INCREMENT,
  MaterialName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Printers (
  PrinterID INT PRIMARY KEY AUTO_INCREMENT,
  PrinterName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Models (
  ModelID INT PRIMARY KEY AUTO_INCREMENT,
  ModelName VARCHAR(255) NOT NULL,
  EstimatedCost DECIMAL(10,2),
  STLFilePath VARCHAR(1024),
  EstimatedPrintTime VARCHAR(50),
  EstimatedFilamentUsage DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS ModelMaterials (
  ModelID INT NOT NULL,
  MaterialID INT NOT NULL,
  FilamentUsageGrams DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ModelID, MaterialID),
  FOREIGN KEY (ModelID) REFERENCES Models(ModelID),
  FOREIGN KEY (MaterialID) REFERENCES Materials(MaterialID)
);

CREATE TABLE IF NOT EXISTS Jobs (
  JobID INT PRIMARY KEY AUTO_INCREMENT,
  JobName VARCHAR(255) NOT NULL,
  UserID INT NOT NULL,
  ModelID INT NOT NULL,
  PrinterID INT NULL,
  PrintDate DATE NOT NULL,
  Status VARCHAR(50),
  Notes TEXT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (ModelID) REFERENCES Models(ModelID),
  FOREIGN KEY (PrinterID) REFERENCES Printers(PrinterID)
);

CREATE TABLE IF NOT EXISTS JobMaterials (
  JobID INT NOT NULL,
  MaterialID INT NOT NULL,
  MaterialUsageGrams DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (JobID, MaterialID),
  FOREIGN KEY (JobID) REFERENCES Jobs(JobID),
  FOREIGN KEY (MaterialID) REFERENCES Materials(MaterialID)
);
